version: "3.8"

name: "zewmsm"

services:
  muppets_server:
    networks:
      - zewmsm
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWD: $POSTGRES_PASSWD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_NAME: $POSTGRES_NAME

      REDIS_GAME_HOST: $REDIS_GAME_HOST
      REDIS_GAME_PORT: $REDIS_GAME_PORT

      GAME_SERVICE_MODE: $GAME_SERVICE_MODE

      TOKEN_IV: $TOKEN_IV
      TOKEN_KEY: $TOKEN_KEY
    ports:
      - "9933:9933"
      - "8083:80"
    restart: unless-stopped
    volumes:
      - "/Users/zewsic/projects/ZewMSM/muppets_content:/app/content"
  redis_muppets:
    image: redis:latest
    networks:
      - zewmsm
    ports:
      - "9141:6379"
    restart: unless-stopped

networks:
  zewmsm:
    external: true